-   repo: https://github.com/FalconSocial/pre-commit-python-sorter
    rev: master
    hooks:
    -   id: python-import-sorter
        args: ['--silent-overwrite']

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.641
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: requirements-txt-fixer
    -   id: flake8
        args: ['--max-line-length=79']
