repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
        args: ['--markdown-linebreak-ext=md']
      - id: end-of-file-fixer
      - id: check-yaml
        args: ['--unsafe']
      - id: check-json
      - id: debug-statements
      - id: requirements-txt-fixer
      - id: check-ast
      - id: flake8
        args: ['--max-line-length=88']

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black